#!/bin/bash

set -e

# Function to handle setup
setup() {
    # Add any additional setup steps here
    echo "Running setup..."

    # Create a temporary directory
    temp_dir=$(mktemp -d)

    # Run Composer to create project and tests in the temporary directory
    composer create-project govcms/govcms:${GOVCMS_VERSION} ${temp_dir} --prefer-dist --remove-vcs && \
    composer create-project govcms/tests:${GOVCMS_TESTS_VERSION} ${temp_dir}/tests --prefer-dist --remove-vcs

    # Copy the contents of the temporary directory to /app
    cp -r ${temp_dir}/* /app/

    # Remove the temporary directory
    rm -rf ${temp_dir}
}

# Function to handle install
install() {
    # Add install steps here
    echo "Running install..."

    # Check if /app/composer.json exists before running composer update
    if [ -f "/app/composer.json" ]; then
        # Run composer update
        echo "Running composer update..."
        cd /app
        composer update --no-interaction --optimize-autoloader
    fi

    # Check if /app/web/sites/default directory exists
    if [ -d "/app/web/sites/default" ]; then
        # Check if /app/web/sites/default/settings.php exists
        if [ -f "/app/web/sites/default/settings.php" ]; then
            echo "Drupal site already installed. Skipping installation."
        else
            # Copy settings.php and set ownership
            echo "Copying settings.php and setting ownership..."
            cp /scripts/drupal/settings.php /app/web/sites/default/settings.php
            chown govcms:govcms /app/web/sites/default/settings.php
            
            # Install the Drupal site using Drush in /app folder
            cd /app
            drush si govcms -y --site-name='GovCMS' --account-pass=password

            # Call config function
            config
        fi
    else
        echo "Error: /app/web/sites/default directory does not exist."
        exit 1
    fi
}

# Function to handle config
config() {
    echo "Running config..."
}

# Function to handle start
start() {
    # Add start steps here
    echo "Running start..."

    # Set ownership of /home/govcms/.cache/composer to govcms:govcms
    chown -R govcms:govcms /home/govcms/.cache/composer

     # Set ownership of /app to govcms:govcms recursively
    chown -R govcms:govcms /app

    # Check if /app/composer.json exists
    if [ ! -f "/app/composer.json" ]; then
        setup
    fi

    # Check if /app/web/sites/default/settings.php exists
    if [ ! -f "/app/web/sites/default/settings.php" ]; then
        # Call install function
        install
    else
        echo "Drupal site already installed. Skipping installation."
    fi

    # Start Supervisor
    supervisord -c /etc/supervisor/conf.d/supervisord.conf
}

# Main entry point
case "$1" in
    setup)
        setup
        ;;
    install)
        install
        ;;
    config)
        config
        ;;
    start)
        start
        ;;
    *)
        echo "Usage: $0 {setup|install|config|start}"
        exit 1
esac

exit 0
