#!/bin/bash

# Run composer update when the container starts
composer update --no-interaction --optimize-autoloader

# Copy settings.php to the desired location and set ownership
cp /scripts/drupal/settings.php /app/web/sites/default/settings.php
chown govcms:govcms /app/web/sites/default/settings.php

# Run the command provided to the entrypoint script
exec "$@"
