#!/bin/bash

# Run Composer to create project and tests
composer create-project govcms/govcms:${GOVCMS_VERSION} . --prefer-dist --remove-vcs --no-install && \
composer create-project govcms/tests:${GOVCMS_TESTS_VERSION} tests --prefer-dist --remove-vcs --no-install

# Start Supervisor with the configured processes
exec "$@"
